############################################################
#
# admin微服务
# web访问端口号 dev: 8003
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M, 超过2M的文件不会被捕获, 需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息   数据源的相关配置
#
############################################################
spring:
  application:
    name: service-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    # Linux 119.29.35.129
    masterUrl: jdbc:mysql://119.29.35.129:3306/golden-years?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2b8
    slaveUrl: jdbc:mysql://106.12.136.221:3306/golden-years?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2b8
    username: root
    password: 990712
    initialization-mode: always
    # 数据源其他配置
    # 初始化连接池的大小
    initialSize: 5
    # 连接池中的最小空闲连接数
    minIdle: 5
    # 连接池中的最大的连接数
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证数据库连接的查询语句
    validationQuery: SELECT 1 FROM DUAL
    # 获取连接的时候测试连接的有效性
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement,
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,wall用于防火墙
    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能; 慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://root:root@119.29.35.129:27017
      database: golden-years
    elasticsearch:
      cluster-name: golden-years-es
      cluster-nodes: 119.29.35.129:9300
  redis:
    database: 0
    host: 119.29.35.129
    port: 6379
    password: 990712
    timeout: 3000
    jedis:
      pool:
        # 控制一个pool可分配多少个jedis实例
        max-active: 100
        #  连接池中最多可空闲maxIdle个连接 这里取值为20 表示即使没有数据库连接时依然可以保持20空闲的连接
        max-idle: 20
        # 最大等待时间:当没有可用连接时, 连接池等待连接被归还的最大时间(以毫秒计数), 超过时间则抛出异常
        max-wait: 3000
  cloud:
    nacos:
      discovery:
        # 配置 Nacos 地址
        server-addr: 127.0.0.1:8848
        # server-addr: 106.12.136.221:8848
        # 配置 service-admin 公网ip 本地部署不用开启
        # ip: 106.12.136.221
        # port: 8003
    sentinel:
      transport:
        dashboard: 106.12.136.221:8888
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'



############################################################
#
# mybatis 配置
#
############################################################
# SqlSessionFactoryBean配置; 多数据源已转移到cn.qingweico.api.config.DruidDataSourceConfig
# mybatis:
  # type-aliases-package: cn.qingweico.pojo          # 所有POJO类所在包路径
  # mapper-locations: classpath:mapper/*.xml         # mapper映射文件
  # config-location: classpath:/mybatis-config.xml   # mybatis配置文件


############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: cn.qingweico.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候, 判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true