############################################################
#
# article微服务
# web访问端口号 dev: 8004
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M,超过2M的文件不会被捕获,需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息   数据源的相关配置
#
############################################################
spring:
  application:
    name: service-article
  datasource:
    type: com.zaxxer.hikari.HikariDataSource             # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/golden-years?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 990712
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长(毫秒), 超过这个时长还没可用的连接则发生SQLException, 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长(毫秒, 超时则被释放(retired), 默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长 (毫秒, 超时而且没被使用则被释放(retired), 默认:30分钟 1800000ms)
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://root:root@119.29.35.129:27017
      database: golden-years
    elasticsearch:
      cluster-name: golden-years-es
      cluster-nodes: 119.29.35.129:9300
  redis:
    database: 0
    host: 119.29.35.129
    port: 6379
    password: 990712
    timeout: 3000
    jedis:
      pool:
        # 控制一个pool可分配多少个jedis实例
        max-active: 100
        # 连接池中最多可空闲maxIdle个连接 这里取值为20 表示即使没有数据库连接时依然可以保持20空闲的连接
        max-idle: 20
        # 最大等待时间:当没有可用连接时, 连接池等待连接被归还的最大时间(以毫秒计数), 超过时间则抛出异常
        max-wait: 3000
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 119.29.35.129
    port: 5672
    username: admin
    password: admin
    virtual-host: golden-years
  cloud:
    nacos:
      discovery:
        server-addr: 119.29.35.129:8848
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: cn.qingweico.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml         # mapper映射文件


############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: cn.qingweico.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候, 判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
# cookie domain
website:
  domain-name: qingweico.cn