############################################################
#
# 用户微服务
# web访问端口号 dev: 8001
#
############################################################
server:
  port: ${port:8001}
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M,超过2M的文件不会被捕获,需要调整此处大小为100MB或者-1即可
    max-threads: 20
    # 配置过大会导致OOM
    # max-http-header-size: 8

############################################################
#
# 配置项目信息   数据源的相关配置
#
############################################################
gy:
  # token 密钥
  token-secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # 登录用户信息保存时间(s)
  token-exp: 1800
  # 登录错误尝试次数
  login-attempts-limit-times: 20
  # 登录错误尝试时间(s)
  login-attempts-limit-seconds: 600
  rate-limit:
    enable: true
    period: 10
    count: 1000
  login-limit:
    period: 10
    count: 10

spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    # time_zone : 设置  set global time_zone = "+8:00";
    masterUrl: jdbc:mysql://127.0.0.1:3306/golden-years?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2b8
    slaveUrl: jdbc:mysql://127.0.0.1:3306/golden-years?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2b8
    username: root
    password: 990712
    initialization-mode: always
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      filters: stat,wall,log4j2
#      max-pool-prepared-statement-per-connection-size: 20
#      use-global-data-source-stat: true
#      # 可配置数据库密码加密操作
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#      filter:
#        config:
#          enabled: true
#        # SQL 防注入
#        wall:
#          config:
#            alter-table-allow: false
#            delete-allow: false
#            drop-table-allow: false
#          enabled: true
#          db-type: mysql
    # 数据源其他配置
    # 初始化连接池的大小
    initialSize: 5
    # 连接池中的最小空闲连接数
    minIdle: 5
    # 连接池中的最大的连接数
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证数据库连接的查询语句
    validationQuery: SELECT 1 FROM DUAL
    # 获取连接的时候测试连接的有效性
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement,
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,wall用于防火墙
    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能; 慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  redis:
    database: 0
    host: 106.12.136.221
    port: 6379
    password: 990712
    timeout: 3000
    jedis:
      pool:
        # 控制一个pool可分配多少个jedis实例
        max-active: 100
        # 连接池中最多可空闲maxIdle个连接 这里取值为20 表示即使没有数据库连接时依然可以保持20空闲的连接
        max-idle: 20
        # 最大等待时间:当没有可用连接时, 连接池等待连接被归还的最大时间(以毫秒计数), 超过时间则抛出异常
        max-wait: 300
  cloud:
    nacos:
      discovery:
        # 配置 Nacos 地址
        server-addr: 106.12.136.221:8848
        # server-addr: 106.12.136.221:8848
        # 配置 service-user 公网ip 本地部署不用开启
        # ip: 106.12.136.221
        # port: 8001
    sentinel:
      transport:
        dashboard: 106.12.136.221:8888
        port: 8719

  ############################################################
  #
  # mybatis 配置
  #
  ############################################################
  # SqlSessionFactoryBean配置; 多数据源已转移到cn.qingweico.api.config.DruidDataSourceConfig
  # mybatis:
  # type-aliases-package: cn.qingweico.pojo          # 所有POJO类所在包路径
  # mapper-locations: classpath:mapper/*.xml         # mapper映射文件
  # config-location: classpath:/mybatis-config.xml   # mybatis配置文件
