############################################################
#
# 文件微服务
# web访问端口号 dev: 8002
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M, 超过2M的文件不会被捕获, 需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: service-files
  datasource:
    # mysql驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    masterUrl: jdbc:mysql://localhost:3306/golden-years?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    slaveUrl: jdbc:mysql://localhost:3306/golden-years?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 990712
    initialization-mode: always
    # 数据源其他配置
    # 初始化连接池的大小
    initialSize: 5
    # 连接池中的最小空闲连接数
    minIdle: 5
    # 连接池中的最大的连接数
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证数据库连接的查询语句
    validationQuery: SELECT 1 FROM DUAL
    # 获取连接的时候测试连接的有效性
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement,
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,wall用于防火墙
    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能; 慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  data:
    mongodb:
      uri: mongodb://root:root@119.29.35.129:27017
      database: golden-years
  cloud:
    nacos:
      discovery:
        server-addr: 119.29.35.129:8848
############################################################
#
#  fastDFS配置信息
#
############################################################
fdfs:
  connect-timeout: 300
  so-timeout: 300
  tracker-list: 119.29.35.129:22122
############################################################
#
#  人脸图片存放位置
#
############################################################
pic:
   path: C:\facePic\